### ISSUE TITLE
Always 110° Celsius

### ISSUE THREAD

**Issue by Barabba11** [belidzs/PreciseLM35#1]
Hi, I tried your example, it sows everytime 110°. Then I connected to an analog line with a trimmer, at very low voltages it goes from 0 to 110, so it works, somehow. 
I tried also the example with reference voltage and I have 466.70° and 5115 as reference.
WHat is wrong here?
I've Arduino UNO powered at 5 volt.
Thank you

**Comment by belidzs** [comment]
You can try to measure the output voltage of your LM50 with a multimeter to make sure it is not faulty and that your circuit is connected correctly. 

When using this component your maximum measurable input voltage on the ADC is 1.1V which translates to 110C, so I'd say either your LM50 is faulty or you're somehow feeding higher voltage to the analog digital converter.
